# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    """
    Modifies the `purchase` model by adding a foreign key field to reference the
    `Product` model, allowing for cascading deletion of purchases when a product
    is deleted.

    Attributes:
        dependencies (List[tuple]): Used to specify the dependencies required for
            the migration to run successfully.
        operations (list[migrationsAlterField]): Defined as a list of migration
            operations, where each operation is an instance of the `AlterField` class.

    """
    dependencies = [
        ('stores', '0002_purchase_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='stores.Product'),
        ),
    ]
