# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    """
    Modifies the `purchase` model by changing the `product` field into a foreign
    key referencing the `Product` model, allowing for cascading deletion of related
    products when a purchase is deleted.

    Attributes:
        dependencies (List[Tuple[str,str]]): Used to specify the migrations that
            must be applied before this migration can be executed.
        operations (List[migrationsAlterField]): Used to define database operations
            for a single migration.

    """
    dependencies = [
        ('stores', '0003_auto_20170507_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, to='stores.Product'),
        ),
    ]
